# Generated by Django 4.1.2 on 2022-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosstream', '0002_event_cleaned_alter_event_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
