# Generated by Django 4.1.2 on 2022-12-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosstream', '0003_event_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='ZZT-CARD', max_length=255)),
                ('world', models.CharField(blank=True, default='', max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
