# Generated by Django 4.2.1 on 2023-07-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdosstream', '0004_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
