# Generated by Django 4.2.1 on 2024-07-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosstream', '0005_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemrule_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=255)),
            ],
        ),
    ]
