# Generated by Django 4.2.1 on 2025-11-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdosstream', '0007_audio_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cleaned',
        ),
        migrations.RemoveField(
            model_name='event',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='processed_at',
        ),
    ]
