# Generated by Django 4.2.1 on 2026-06-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosstream', '0008_remove_event_cleaned_remove_event_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
