# Generated by Django 4.2.1 on 2026-06-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdosstream', '0009_game_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_card',
            name='data',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
